### ISSUE TITLE
Errors in console 

### ISSUE THREAD

**Issue by mmchast88** [thinhvo0108/react-paypal-express-checkout#11]
![screen shot 2017-10-26 at 9 16 21 pm](https://user-images.githubusercontent.com/27980151/32083740-0ab06bc0-ba93-11e7-9f42-13abad8222ec.png)

Im getting these errors in the console.  How do I resolve them?  I am new to React.

**Comment by thinhvo0108** [comment]
Could you please make sure version 1.0.3 is installed (please check your package.json file) and update the library if necessary!

**Comment by mmchast88** [comment]
@thinhvo0108 yes, I have that version installed.  But, I am still getting the errors?

**Comment by mmchast88** [comment]
@thinhvo0108 and the pop-up doesnt come up? Do you know why that is happening?  I am not getting the errors in red anymore.  I have done a Paypal API in the past with regular javascript and it worked.

**Comment by thinhvo0108** [comment]
@mmchast88 it seems that sometimes the original Paypal script has error or timeout or something like that. Actually, this library relies much on their script, I mean the official Paypal Script. Can you make sure your internet speed is stable, then try again? Thanks (or maybe you can clear cache of your browser)

**Comment by mmchast88** [comment]
@thinhvo0108 I tried a different browser and got these errors...

![screen shot 2017-10-26 at 10 00 27 pm](https://user-images.githubusercontent.com/27980151/32084783-3690e494-ba99-11e7-875e-144c6da95766.png)

**Comment by thinhvo0108** [comment]
Seems that version 1.0.3 is not so stable yet, I will fix this later when I have time. In the mean time, please delete this 1.0.3 version and use 1.0.1
Please also keep me updated for other issues you may have!

**Comment by mmchast88** [comment]
@thinhvo0108 I am using version 1.0.1 and I am still getting the same errors.

**Comment by thinhvo0108** [comment]
@mmchast88 oh really, then this problem may originally come from the Paypal script itself!
I will try to investigate the problem later, thanks!

**Comment by tommaso1** [comment]
Me too, can't open popup, same errors, no way to make PayPal work with react

**Comment by tommaso1** [comment]
![image](https://user-images.githubusercontent.com/18684459/32559563-c3da0552-c4a7-11e7-8949-b2d42099d82f.png)

**Comment by thinhvo0108** [comment]
Hi all!

Just like other issue, this one also comes from original Paypal script
itself (the "shipping" attribute has problem)
Could you guys please delete the current version of my library, and
re-install it using version 1.0.1 (more stable):
"npm install --save react-paypal-express-checkout@1.0.1"

Thanks!

**Comment by thinhvo0108** [comment]
I have just updated the latest version (@1.0.4)
Could you guys please try using it? Thanks!

**Comment by thinhvo0108** [comment]
Close this issue, which was probably fixed in version @1.0.4
