### ISSUE TITLE
Error Unrecognized prop: shipping

### ISSUE THREAD

**Issue by brave-merida** [thinhvo0108/react-paypal-express-checkout#12]
![screenshot at oct 31 09-57-53](https://user-images.githubusercontent.com/30062357/32204047-0530fc72-be22-11e7-8f42-171f90d222c3.png)
Hi,
I met the error, please help me.
My code is 
```
const client = {
			sandbox:    'YOUR-SANDBOX-APP-ID',
			production: 'YOUR-PRODUCTION-APP-ID',
		}
<PaypalExpressBtn 
                env={paypalConfig.env} 
                client={client} 
                currency={paypalConfig.currency} 
                shipping={0} 
                onError={this.onError} 
                onSuccess={this.onSuccess} 
                onCancel={this.onCancel} 
                total={140} />
```

**Comment by thinhvo0108** [comment]
@brave-merida Thanks for reporting this problem!
This seems to come from the official Paypal script itself!

Could you please uninstall this latest version, and re-install with version 1.0.1, which is more stable
`npm install --save react-paypal-express-checkout@1.0.1`

Thanks

**Comment by brave-merida** [comment]
Great,
Thank you very much!
