### ISSUE TITLE
ReferenceError: paypal is not defined

### ISSUE THREAD

**Issue by bakamaru** [thinhvo0108/react-paypal-express-checkout#13]
I've tried same way as mentioned in example but whenever I load page,I got ReferenceError: paypal is not defined which is not in global context.

**Comment by thinhvo0108** [comment]
This seems to be a problem with Paypal script itself!

I think when Paypal script is slow in loading and returning its paypal
object, this issue will happen!

I will try to check this issue again when I have time, could you please try
again a few times! Or maybe delete the current version, and reinstall with
version 1.0.1 (npm install --save react-paypal-express-checkout@1.0.1)

**Comment by thinhvo0108** [comment]
I have just updated the latest version (@1.0.4)
Could you please try using it? Thanks!

**Comment by thinhvo0108** [comment]
Close this issue, which was probably fixed in version @1.0.4
