### ISSUE TITLE
Paypal button click doesn't trigger pop-up 

### ISSUE THREAD

**Issue by danniboi82** [thinhvo0108/react-paypal-express-checkout#18]
Trying to use this react-paypal-express-checkout package on site.  
Paypal button component to store the code and export the component to parent component to render button on it. 
However, when I press the rendered paypal button console gives me the following errors.
![image](https://user-images.githubusercontent.com/31552887/34969090-f305cd48-fa21-11e7-92f6-d78e5144b297.png)

I was expecting the pop-up to login to paypal.... 
Sorry I am pretty new to react need some guidance! Thanks!

**Comment by danniboi82** [comment]
Here's some additional information 
PayPalButton Component Code : 
`import React, {Component} from 'react';
import PaypalExpressBtn from 'react-paypal-express-checkout';

 
export default class PayPalButton extends Component {
    render() {
        const client = {
            sandbox:    'XXXXXXXXXX',
            production: 'YOUR-PRODUCTION-APP-ID',
        }	
        return (
            <PaypalExpressBtn client={client} currency={'USD'} total={1.00} />
        );
    }
}    `

Parent Component Code : 

`import React, { Component } from 'react';
import FlatButton from 'material-ui/FlatButton';
import './CheckOutPage.css';
import Paper from 'material-ui/Paper'
import PayPalButton from './PayPalButton/PayPalButton';

class checkOutPage extends Component {
    
    deleteProductHandler = (id) => {
        const ogProductList = this.state.dummyData;
        ogProductList.splice( id, 1);
        const updatedProductList = ogProductList;
        this.setState({
            dummyData: updatedProductList
        })
        console.log(this.state.dummyData);
    }

    render() {
        return (
            <div className='CheckOutPageDiv'>
                <div>
                    <h1>CHECKOUT PAGE</h1>
                </div>
                {this.state.dummyData.map((card, id) => (
                    <Paper
                        zDepth={5}
                        className='ProductPaper'
                        key={card.id}
                    >
                        <div className='ImageDiv'>
                            <img className='ProductImage' src={card.img} alt="" />
                        </div>
                        <div className='ProductDescription'>
                            Description: {card.title}
                        </div>
                        <FlatButton label='Remove'
                        onClick={()=>this.deleteProductHandler(id)} />
                    </Paper>
                ))}
                <div className='PlaceOrderDiv'>
                    <FlatButton style={{ backgroundColor: 'blue' }} label='Place Order' />
                    <PayPalButton />
                </div>

            </div>
        )
    }
}`

**Comment by thinhvo0108** [comment]
Have you registered for your own Paypal's application ID yet?
If not, please follow their instruction for getting a new sandbox ID!
Thanks

**Comment by danniboi82** [comment]
Thanks I'll definitely read it! I love reading documentations lol

**Comment by danniboi82** [comment]
Yea, fixed the issue... tried downgrading to 1.0.1 but it kept throwing a scirptLoad error so I tried removing the shipping props from the 1.0.3 package files and it started working...

**Comment by thinhvo0108** [comment]
It's good to hear!
I will improve this library because of that "shipping" issue asap when I
have time!
If you feel OK with the current, please also close this issue for me,
thanks!

**Comment by zaw-hlaing-bwar** [comment]
@danniboi82 
can you give a guideline of how did you remove shipping props?
using 1.0.1 keep throwing  scirptLoad error on heroku server.
Thanks.

**Comment by yannvr** [comment]
@zaw-hlaing-bwar Just remove the prop from the render in the source

**Comment by thinhvo0108** [comment]
I have just updated the latest version (@1.0.4)
Could you please try using it? Thanks!

**Comment by thinhvo0108** [comment]
Close this issue, which was probably fixed in version @1.0.4
