### ISSUE TITLE
Question about React.createClass been deprecated

### ISSUE THREAD

**Issue by jmaguirrei** [thinhvo0108/react-paypal-express-checkout#2]
Hello, I think it may be an issue with paypal xComponent creating a React Component with createClass method, but I would like to know if is there any solution to this warning:

`React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

Thanks,

**Comment by vuuet** [comment]
@jmaguirrei use "class ABC extends React.Component" instead.

**Comment by jmaguirrei** [comment]
@vuuet Looks like the script `https://www.paypalobjects.com/api/checkout.js` is using createClass, not your wrapper.

I wonder if there is any workaround, because React 16 is 'ad portas'.

For example, is it possible to just copy this script inside the project and modify the createClass in place?

Thanks.

![createclass](https://user-images.githubusercontent.com/11958637/29127800-1dd9d50a-7cf0-11e7-8506-6a31d26c42c2.png)

**Comment by thinhvo0108** [comment]
I close this issue since the warning comes from Paypal's original script `https://www.paypalobjects.com/api/checkout.js`
This was also inactive for a while!

Thanks
