### ISSUE TITLE
can not open popup checkout

### ISSUE THREAD

**Issue by khoaanh2212** [thinhvo0108/react-paypal-express-checkout#20]
i got this message when try to integrate your component
![image](https://user-images.githubusercontent.com/13479365/36638183-574b2370-1a20-11e8-9b1f-bfbe45cbed36.png)
i put sandbox app id.
would you like to help me fix it?thanks

**Comment by thinhvo0108** [comment]
I have just updated the latest version (@1.0.4)
Could you please try using it? Thanks!

**Comment by thinhvo0108** [comment]
Close this issue, which was probably fixed in version @1.0.4, or was related to other problem, not about this component itself, thanks!
