### ISSUE TITLE
Many Errors

### ISSUE THREAD

**Issue by edwardva** [thinhvo0108/react-paypal-express-checkout#21]
Hi. i follow all your examples step by step and 

- First div is not reconized by React
- Second. i quit div but it error show me undefined is not an object (evaluating 'window.navigator.userAgent.match')

Thanks in advance

**Comment by thinhvo0108** [comment]
I have just updated the latest version (@1.0.4)
Could you please try using it? Thanks!

**Comment by thinhvo0108** [comment]
Close this issue, which was probably fixed in version @1.0.4
