### ISSUE TITLE
forwarding to a return url after payment

### ISSUE THREAD

**Issue by gilesgerman** [thinhvo0108/react-paypal-express-checkout#27]
I have setup the return url in account settings but it doesn't return to where I have directed it.  Is it possible to write this into the code to direct after a successful payment?

**Comment by thinhvo0108** [comment]
Sorry for keeping you waiting, #22 has been merged, and latest version @1.0.5 has just been updated on NPM, too, thanks!
You can use that version, with full transaction object supported
