### ISSUE TITLE
Certificate distrusted in M70 error

### ISSUE THREAD

**Issue by grahamyesfit** [thinhvo0108/react-paypal-express-checkout#28]
We've been receiving the following warning from our React Web Site for the last several months:

```
The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
```

Starting yesterday, we've had dozens of Chrome users reporting that the PayPal modal no longer comes up. Please help.

**Comment by thinhvo0108** [comment]
This seems to be a problem from Paypal site themselves, if so, Paypal team
may have solution soon, because my library's backbone is the Paypal script,
original one!

Thanks

**Comment by grahamyesfit** [comment]
@thinhvo0108, thanks for the quick reply! This is what I figured, I was just hoping you had some kind of inside track! I hope there's a solution soon, I think a lot of people are having this issue.

**Comment by thinhvo0108** [comment]
Hopefully it will be resolved soon, let's wait and hear from Paypal first!
Thanks again!
