### ISSUE TITLE
Since installing and using, I'm not getting this error.

### ISSUE THREAD

**Issue by Gmunker** [thinhvo0108/react-paypal-express-checkout#3]
> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

I see that you are requiring prop-types and not from the react package so i'm not sure if there is another place i did not see that is requiring it.

**Comment by thinhvo0108** [comment]
Sorry I was busy lately! I have no idea why that warning showed up, "prop-types package from npm" is used from the beginning! 
Could you please try updating this library to the latest version (1.0.3) that I published today (with react 16) to see if the warning persist!
Thanks

**Comment by thinhvo0108** [comment]
I close this issue since this was inactive for a while, as well as `prop-types` package from npm was used from the beginning!

Thanks
