### ISSUE TITLE
How can we put a custom button instead of Paypal's button?

### ISSUE THREAD

**Issue by pagesrichie** [thinhvo0108/react-paypal-express-checkout#33]
How can we put a custom button (my own button component) instead of Paypal's button?  I'm using semantic ui react and i want to use my own button component instead of any of paypal's buttons.

**Comment by thinhvo0108** [comment]
I think we cannot do this for now, as the button is from Paypal themselves, not a normal DOM which can be controlled fully from our side ^^
However, I think we can try to use the `style` props as much as possible
