### ISSUE TITLE
error on redirect

### ISSUE THREAD

**Issue by Gmunker** [thinhvo0108/react-paypal-express-checkout#4]
Everything is still working just fine, but i'm getting this error. 
I setup a redirect with react router in button component. When onSuccess it updates my redux store, once the prop of paid shows true, it redirects to a thank you exiting page.

Once it redirects it throws this error.

`
ppxo_unhandled_error 

Object {stack: "Error: No response from window - cleaned up↵    at…://www.paypalobjects.com/api/checkout.js:7250:24)", errtype: "[object Error]", timestamp: 1499546983665, windowID: "aff4474a47", pageID: "d0ea31b50d"…}

clean.js:17 Uncaught Error: No response from window - cleaned up
    at Object.cleanUpWindow (clean.js:17)
    at drivers.js:90
    at Object.run (base.js:52)
    at Object.all (base.js:67)
    at index.js:1163
    at Function.ZalgoPromise.try (promise.js:291)
    at ParentComponent.destroy (index.js:1159)
    at index.js:568
    at Function.ZalgoPromise.try (promise.js:291)
    at promise.js:222
    at promise.js:144
    at ZalgoPromise.dispatch (promise.js:183)
    at ZalgoPromise.then (promise.js:211)
    at ZalgoPromise.finally (promise.js:221)
    at index.js:565
    at fn.js:28
    at checkWindowClosed (dom.js:179)
    at runInterval (util.js:188)
`

**Comment by thinhvo0108** [comment]
@Gmunker Sorry I was busy lately, have you found solution for this error yet?

It seems that the Paypal window object was not closed properly when your page redirected to another one!

Since my library is based mostly on https://www.paypalobjects.com/api/checkout.js (or course), most of the problems come from their side, so we can not be 100% flexible to fix all of them!

**Comment by thinhvo0108** [comment]
@Gmunker  In my opinion, you can try the ComponentWillUnmount() in your main React component to get rid of that!

I close this issue since this was inactive for a while

Thanks!
