### ISSUE TITLE
Forking and building

### ISSUE THREAD

**Issue by tfulton** [thinhvo0108/react-paypal-express-checkout#5]
Hi Thinh,

I'm a developer at PayPal, and would like to fork and use your repo.  Excuse my naiveté, but any way you could post local build instructions as you may know them?

Todd

**Comment by thinhvo0108** [comment]
Hi Todd,

Thanks for your message!
Please go ahead, just fork and use my repo, and please also feel free to send me pull requests if possible, too!

About the local build instruction, sorry I didn't get what you meant yet, can you read my tutorial, there are simple and full examples, is that what you need?

Thinh

**Comment by tfulton** [comment]
Hey!  I've forked the repo and want to test out local changes as an npm
dependency.  My package.json:

```
  "dependencies": {
    ...
    "react-dom": "^15.5.4",
    "react-paypal-express-checkout":
"file:../../react-paypal-express-checkout",
    ...
  },
```

For the build of the ./dist/ files in your project, I've tried `npm
prepublish` but, my version of npm complains its deprecated.  THIS is the
part I was trying to get your help on.  Not a big deal, really.

Nice work btw!  Its really the only react example of PayPal checkout that
seems to exist!!!!  And I work at the place!!


Todd

**Comment by thinhvo0108** [comment]
Hi Todd,

I was busy lately, have you got this work yet in your local environment?

**Comment by tfulton** [comment]
Yes, I did.  It works great.  Thanks!!

**Comment by thinhvo0108** [comment]
Thanks for your reply!
Glad you had it working!
I will close this ticket, then!
